### ISSUE TITLE
Suggestions on the initial color of icon library

### ISSUE THREAD

**Issue by Barry-Flynn** [Richard9394/MingCute#52]
Hello friend, I really like this icon library, but during use, I found that you have set an initial value of '# 09244b' for all CSS icons, which may cause confusion for developers. Even though colors can be style overridden during development, I think icon fonts without initial color settings (inheriting parent elements) are more suitable, right?

你好朋友，非常喜欢这个图标库，但是在使用过程中发现你们为所有的CSS图标设置了初始值 '#09244b'，这可能会为开发者带来困扰，即便开发过程中可以对颜色进行样式覆盖，但我觉得没有设置初始颜色的图标字体（继承父元素）更合适，不是吗？

**Comment by Barry-Flynn** [comment]
目前在项目中，我使用下方 CSS 对图标颜色进行了强制覆盖：
```css
// 强制覆盖 mingcute_icon 图标库的初始字体颜色
// 匹配所有以 mgc_ 开头的类名和包含 mgc_ 的类名的::before 伪元素
[class^='mgc_']::before,
[class*=' mgc_']::before {
  // 继承父元素的字体颜色
  color: inherit !important;
}
```
